### ISSUE TITLE
Visibility of global variables initied with 'set' 

### ISSUE THREAD

**Issue by Icehold** [kdbinsidebrains/plugin#107]
Currently if varialbe inited with set function plugin will set its usages as undefined
eg
init:{[] `my_var set 15};
init[];
my_var; // marked as underfined

**Comment by smklimenko** [comment]
yes, I know about that and couldn't fix that initially as there are too many questions around that when we talk about symbols as it could be anything, by the fact, like renaming, initial value (_{x:`my_var; x set 15}_) and so on.

Maybe should do another try and at least support the simple case as in your example but no timeline here, sorry
