### ISSUE TITLE
Changed Settings Not Persisting

### ISSUE THREAD

**Issue by dannicholls244** [kdbinsidebrains/plugin#36]
Currently using Community version 2021.3. KdbInsideBrains version: 1.3.0. Windows.

Settings not persisted after IDE restart.

%APPDATA%\JetBrains\IdeaIC2021.3\options\kdb-settings.xml is showing the preserved setting, but after IDE restart, settings are reset to default.

Before restart:
![Before Restart](https://user-images.githubusercontent.com/20861018/176702909-d9c182c2-c4d1-4857-b277-9a8a53e09f30.png)
 
After restart:
![After Restart](https://user-images.githubusercontent.com/20861018/176702905-f712c41d-b433-40a9-92c3-b98d2bfb24a5.png)

**Comment by smklimenko** [comment]
Fixed in 1.3.1. Will be available after JetBrains approval or you can use direct link: https://plugins.jetbrains.com/plugin/16746-kdbinsidebrains/versions/stable/192385
