### ISSUE TITLE
Incorrect parsing of `system "l ","..."` command

### ISSUE THREAD

**Issue by darrenwsun** [kdbinsidebrains/plugin#61]
Hi authors, 

First of all, great thanks for building this awesome plugin!

Here is a weird parsing issue that seems to affect only load command. Behind the scene it seems trying to validate if the file exists, but it's impossible to do this well in all cases, especially when the path is dynamic, e.g. the path contains `getenv` call for an environment variable.
![image](https://user-images.githubusercontent.com/103033391/209747761-3e5f5fc3-16e9-40bf-b6a8-773580de283a.png)

I'd rather not to have this validation to avoid noises. What's your opinion/suggestion?

**Comment by smklimenko** [comment]
so, it's not parsing, actually, by an inspection rule and yes, it checks that file exist.  You can turn off this particular one but it's a bug anyway. 

By the fact 'system "l " is parsed not like a command but like '\l' function here and I was sure I've fixed that but looks like not finally.

Will check it shortly as have more changes comming these days.

**Comment by smklimenko** [comment]
fixed in 3.4.0. Will be available after JetBrains approval: https://plugins.jetbrains.com/plugin/16746-kdbinsidebrains/versions/stable/271054
