### ISSUE TITLE
Unable to launch create chat window after the latest upgrade. 3.6.2

### ISSUE THREAD

**Issue by eyufit** [kdbinsidebrains/plugin#67]
![image](https://user-images.githubusercontent.com/118200380/219424427-e0ed4f54-e0b7-4db5-b50a-2d557043721a.jpg)

**Comment by smklimenko** [comment]
so, it doesn't work in old IDEA version, prior 2022.3 but as you are not the first one, I've fixed that in 3.6.3 and it will be availalbe after JetBrain's approval (about 2 days). If you wish, you can download and install it manually: https://plugins.jetbrains.com/plugin/16746-kdbinsidebrains/versions/stable/293860
