### ISSUE TITLE
defining a function with break between lines does not work

### ISSUE THREAD

**Issue by je33y** [kdbinsidebrains/plugin#74]
when i define a function, the statement below works:
my_function:{til x}

but this way of defining a function does not work:
my_function2:
{til x}

looking forward to this issue to be fixed.

**Comment by smklimenko** [comment]
it's not an issue and won't be fixed. Each line is treated as separate statement in Q so formally you have 2 independent statements.

If you create a file named test.q, add your code inside and try start the file with q test.q you'll get the following error:
'my_function2
  [2]  test.q:1: my_function2:
                         ^
  [0]  (<load>)

  )
