### ISSUE TITLE
Is it possible to display the line of code that raises an error?

### ISSUE THREAD

**Issue by flcong** [kdbinsidebrains/plugin#86]
In the q console, if there is an error within a function. The line of code triggering the error is displayed, together with the error info (started with `'`). Yet, in kdbinsidebrains, for such cases, only the error info is displayed. So I am wondering if it is possible to show the line of code with the error as well. I am not sure if this info is available in the kdb Java API.

**Comment by smklimenko** [comment]
nope, sorry. KDB doesn't provide remote debugging ability and there is no way to match source code with executed line so you can only execute expression by expression manually or start local instance and use local debugging features as described here: https://code.kx.com/q/basics/debug/
