### ISSUE TITLE
Feature request: copy the whole table to clipboard not just selected rows

### ISSUE THREAD

**Issue by r-hou** [kdbinsidebrains/plugin#97]
And could you pls also leave a EVM address here since I cannot donate through paypal due to unknown reason.

**Comment by smklimenko** [comment]
you can use Ctrl+A to select all and Ctr+C to copy the content.

or you can remove all select and you 'Copy' button on the toolbar to copy content of the whole table:
![image](https://github.com/kdbinsidebrains/plugin/assets/3913096/fd8dcaa1-673b-4a73-b32f-eb8a0a17f301)
