### ISSUE TITLE
KDB Inspector Problem

### ISSUE THREAD

**Issue by freeclb** [kdbinsidebrains/plugin#98]
Error: Instance structure can't be loaded: .db.Ax.290.130973!
but actually 290.130973 is a symbol like `290.130973 and it's a dict key in .db.Ax

**Comment by smklimenko** [comment]
you can always check all keys of a dict using command **key**:
**key .db.Ax**

Please make sure that you have symbol `290.130973 in the keys or copy the context of the keys here.

If I have dict with `290.130973 as a key:
![image](https://github.com/user-attachments/assets/6b595363-64ca-4fcf-bcb5-2910596fd7c9)

it's correctly shown in the Inspector for me:
![image](https://github.com/user-attachments/assets/79b6dfed-fed5-4cdf-b217-44f8a4866cce)

Feel free to reopen with more details
